name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:  # Permite executar manualmente

permissions:
  contents: write  # Permissão para escrever na branch output

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create dist directory
        run: mkdir -p dist
      
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: joaopintoferreira  # SEU NOME DE USUÁRIO
          outputs: |
            dist/github-contribution-grid-snake.svg
      
      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          force_orphan: true
